#!/usr/bin/env node
// Tier A generator: CLI reference. Extracts the `USAGE` heredoc from
// packages/cli/src/cli.ts as *source text* via ts-morph — same philosophy
// as mcp.ts: read-only AST parsing, never importing/executing @vorlyn/cli
// (which has no library export surface anyway, only a `bin` entrypoint).

import { Project, SyntaxKind } from 'ts-morph';
import type { NoSubstitutionTemplateLiteral } from 'ts-morph';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, REFERENCE_DIR } from './paths.js';

const CLI_TS = path.join(REPO_ROOT, 'packages/cli/src/cli.ts');
const OUT = path.join(REFERENCE_DIR, 'cli-reference.md');

function extractUsage(): string {
  const project = new Project({
    skipAddingFilesFromTsConfig: true,
    skipFileDependencyResolution: true,
    compilerOptions: { allowJs: true },
  });
  const sourceFile = project.addSourceFileAtPath(CLI_TS);

  for (const decl of sourceFile.getVariableDeclarations()) {
    if (decl.getName() !== 'USAGE') continue;
    const init = decl.getInitializer();
    if (init?.getKind() === SyntaxKind.NoSubstitutionTemplateLiteral) {
      return (init as NoSubstitutionTemplateLiteral).getLiteralText();
    }
  }
  throw new Error(`Could not find an exported \`USAGE\` template literal in ${CLI_TS}`);
}

export function toMarkdown(usage: string): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('title: CLI reference');
  lines.push(
    'description: Generated by scripts/gen-docs/src/cli.ts from packages/cli/src/cli.ts. Do not hand-edit.',
  );
  lines.push('---');
  lines.push('');
  lines.push('> Generated from `packages/cli/src/cli.ts`’s `USAGE` text by `pnpm gen:cli`.');
  lines.push('');
  lines.push('```');
  lines.push(usage);
  lines.push('```');
  lines.push('');
  return lines.join('\n');
}

export function generateCliReference(): { usage: string; markdown: string } {
  const usage = extractUsage();
  const markdown = toMarkdown(usage);
  return { usage, markdown };
}

export function main(): void {
  const { markdown } = generateCliReference();
  mkdirSync(REFERENCE_DIR, { recursive: true });
  writeFileSync(OUT, markdown);
  console.log(`Extracted USAGE from ${path.relative(REPO_ROOT, CLI_TS)}`);
}

if (import.meta.url === `file://${process.argv[1] ?? ''}`) {
  main();
}
